const fs = require('fs');
let content = fs.readFileSync('.sisyphus/plans/codebuddy-runtime.md', 'utf8');

// Translate content to Chinese while keeping technical terms, YAML keys, and structure intact
content = content
  .replace('Add CodeBuddy IDE as 7th GSD Runtime', '添加 CodeBuddy IDE 作为第 7 个 GSD 运行时')
  .replace('Quick Summary', '快速摘要')
  .replace('Add CodeBuddy IDE (腾讯云代码助手) as a new supported runtime for GSD. CodeBuddy is architecturally the closest runtime to Claude Code — same tool names, same hooks spec, same command format — making this a relatively straightforward addition following the Claude/Gemini code path.', '将 CodeBuddy IDE（腾讯云代码助手）添加为 GSD 的新支持运行时。CodeBuddy 在架构上是与 Claude Code 最接近的运行时——工具名称相同、hooks 规范相同、命令格式相同——这使得按照 Claude/Gemini 代码路径添加它相对简单。')
  .replace('Deliverables', '交付物')
  .replace('updated with', '更新并添加')
  .replace('flag, directory mapping, agent conversion, install/uninstall logic', '标志、目录映射、agent 转换、安装/卸载逻辑')
  .replace('comprehensive test file', '综合测试文件')
  .replace('updated with CodeBuddy sections', '更新 CodeBuddy 相关章节')
  .replace('Estimated Effort', '预估工作量')
  .replace('Medium', '中等')
  .replace('Parallel Execution', '并行执行')
  .replace('YES - 3 waves', '是 - 3 个阶段')
  .replace('Critical Path', '关键路径')
  .replace('Context', '上下文')
  .replace('Original Request', '原始请求')
  .replace('Interview Summary', '访谈摘要')
  .replace('Key Discussions', '关键讨论')
  .replace('Research Findings', '研究发现')
  .replace('Metis Review', 'Metis 审查')
  .replace('Identified Gaps (addressed)', '识别出的差距（已解决）')
  .replace('Work Objectives', '工作目标')
  .replace('Core Objective', '核心目标')
  .replace('Concrete Deliverables', '具体交付物')
  .replace('Definition of Done', '完成定义')
  .replace('Must Have', '必须具备')
  .replace('Must NOT Have (Guardrails)', '绝不能有（护栏）')
  .replace('Verification Strategy', '验证策略')
  .replace('ZERO HUMAN INTERVENTION — ALL verification is agent-executed. No exceptions.', '零人工干预 — 所有验证均由 agent 执行。没有例外。')
  .replace('Test Decision', '测试决策')
  .replace('Infrastructure exists', '基础设施存在')
  .replace('Automated tests', '自动化测试')
  .replace('Framework', '框架')
  .replace('QA Policy', 'QA 策略')
  .replace('Every task MUST include agent-executed QA scenarios.', '每个任务必须包含由 agent 执行的 QA 场景。')
  .replace('Evidence saved to', '证据保存至')
  .replace('Execution Strategy', '执行策略')
  .replace('Parallel Execution Waves', '并行执行阶段')
  .replace('Start Immediately — foundation functions', '立即开始 — 基础函数')
  .replace('After Wave 1 — core install/uninstall logic', '阶段 1 之后 — 核心安装/卸载逻辑')
  .replace('After Wave 2 — tests + docs', '阶段 2 之后 — 测试 + 文档')
  .replace('After ALL tasks — verification', '所有任务之后 — 验证')
  .replace('Parallel Speedup: ~40% faster than sequential', '并行加速：比串行快约 40%')
  .replace('Max Concurrent:', '最大并发：')
  .replace('Dependency Matrix', '依赖矩阵')
  .replace('Agent Dispatch Summary', 'Agent 调度摘要')
  .replace('TODOs', '待办事项')
  .replace('CLI Flag Parsing + Directory Mapping Functions', 'CLI 标志解析 + 目录映射函数')
  .replace('CodeBuddy Agent Conversion Function', 'CodeBuddy Agent 转换函数')
  .replace('Test-Mode Exports Update', '测试模式导出更新')
  .replace('Install Function — CodeBuddy Branch', '安装函数 — CodeBuddy 分支')
  .replace('Uninstall Function — CodeBuddy Branch', '卸载函数 — CodeBuddy 分支')
  .replace('Interactive Prompt + finishInstall Updates', '交互式提示 + finishInstall 更新')
  .replace('Comprehensive Test File', '综合测试文件')
  .replace('README Updates (EN + ZH-CN)', 'README 更新 (EN + ZH-CN)')
  .replace('What to do', '要做什么')
  .replace('Must NOT do', '绝不能做')
  .replace('Recommended Agent Profile', '推荐的 Agent 配置文件')
  .replace('Category', '类别')
  .replace('Skills', '技能')
  .replace('Parallelization', '并行化')
  .replace('Can Run In Parallel', '可并行运行')
  .replace('Parallel Group', '并行组')
  .replace('Blocks', '阻塞')
  .replace('Blocked By', '被阻塞')
  .replace('References', '参考')
  .replace('Pattern References', '模式参考')
  .replace('Test References', '测试参考')
  .replace('API/Type References', 'API/类型参考')
  .replace('External References', '外部参考')
  .replace('Acceptance Criteria', '验收标准')
  .replace('QA Scenarios', 'QA 场景')
  .replace('Commit', '提交')
  .replace('Message', '消息')
  .replace('Files', '文件')
  .replace('Pre-commit', '预提交')
  .replace('Final Verification Wave', '最终验证阶段')
  .replace('MANDATORY — after ALL implementation tasks', '强制性 — 在所有实现任务之后')
  .replace('4 review agents run in PARALLEL. ALL must APPROVE. Rejection → fix → re-run.', '4 个审查 agent 并行运行。必须全部批准。拒绝 → 修复 → 重新运行。')
  .replace('Plan Compliance Audit', '计划合规性审计')
  .replace('Code Quality Review', '代码质量审查')
  .replace('Real Manual QA', '真实手动 QA')
  .replace('Scope Fidelity Check', '范围保真度检查')
  .replace('Commit Strategy', '提交策略')
  .replace('Success Criteria', '成功标准')
  .replace('Verification Commands', '验证命令')
  .replace('Final Checklist', '最终清单');

// Fix task descriptions selectively
content = content
  .replace('Add `hasCodebuddy` flag parsing at line 65 area', '在第 65 行区域添加 `hasCodebuddy` 标志解析')
  .replace('Add `if (hasCodebuddy) selectedRuntimes.push(', '在第 83 行区域添加 `if (hasCodebuddy) selectedRuntimes.push(')
  .replace('Add `\'codebuddy\'` to `selectedRuntimes` when `hasAll` is true at line 74', '当 `hasAll` 为 true 时，在第 74 行将 `\'codebuddy\'` 添加到 `selectedRuntimes` 中')
  .replace('Add `getDirName(\'codebuddy\')` returning', '添加 `getDirName(\'codebuddy\')` 并返回')
  .replace('Add `getConfigDirFromHome(\'codebuddy\', isGlobal)` returning', '添加 `getConfigDirFromHome(\'codebuddy\', isGlobal)` 并返回')
  .replace('Add `getGlobalDir(\'codebuddy\', explicitDir)` block at line 218-227 area, supporting `CODEBUDDY_CONFIG_DIR` env var, defaulting to `~/.codebuddy`', '在第 218-227 行区域添加 `getGlobalDir(\'codebuddy\', explicitDir)` 块，支持 `CODEBUDDY_CONFIG_DIR` 环境变量，默认值为 `~/.codebuddy`')
  .replace('Update the banner text at line 260 to include "CodeBuddy" in the list of supported runtimes', '更新第 260 行的横幅文本，将 "CodeBuddy" 包含在支持的运行时列表中')
  .replace('Do NOT modify the `--both` legacy flag (line 67)', '不要修改 `--both` 遗留标志（第 67 行）')
  .replace('Do NOT add CodeBuddy to `--both`', '不要将 CodeBuddy 添加到 `--both`')
  .replace('Create `convertClaudeAgentToCodebuddyAgent(content)` function in `bin/install.js`', '在 `bin/install.js` 中创建 `convertClaudeAgentToCodebuddyAgent(content)` 函数')
  .replace('The function should:', '该函数应该：')
  .replace('Extract frontmatter and body using existing `extractFrontmatterAndBody(content)`', '使用现有的 `extractFrontmatterAndBody(content)` 提取 frontmatter 和正文')
  .replace('Parse existing fields: `name`, `description`, `tools` (keep as-is since tool names are identical)', '解析现有字段：`name`、`description`、`tools`（保持原样，因为工具名称相同）')
  .replace('Inject two new frontmatter fields:', '注入两个新的 frontmatter 字段：')
  .replace('Reconstruct frontmatter with all original fields plus the two new ones', '使用所有原始字段加上这两个新字段重构 frontmatter')
  .replace('Return `${newFrontmatter}\n${body}`', '返回 `${newFrontmatter}\n${body}`')
  .replace('Export the function in test-mode exports (line 3010-3044)', '在测试模式导出中导出该函数（第 3010-3044 行）')
  .replace('Do NOT create tool name mapping — tools are identical to Claude Code', '不要创建工具名称映射 — 工具与 Claude Code 完全相同')
  .replace('Do NOT modify existing agent conversion functions', '不要修改现有的 agent 转换函数')
  .replace('Do NOT add complex content conversion — just frontmatter injection', '不要添加复杂的内容转换 — 仅注入 frontmatter')
  .replace('Add all new CodeBuddy-specific functions to the test-mode exports block at line 3010-3044', '将所有新的 CodeBuddy 特定函数添加到第 3010-3044 行的测试模式导出块中')
  .replace('Functions to export:', '要导出的函数：')
  .replace('Note: `getDirName`, `getGlobalDir`, `getConfigDirFromHome` are already exported', '注意：`getDirName`、`getGlobalDir`、`getConfigDirFromHome` 已经被导出了')
  .replace('Do NOT export functions that don\'t exist yet', '不要导出还不存在的函数')
  .replace('Do NOT modify existing exports', '不要修改现有的导出')
  .replace('In `install()` function (line 2394), add `const isCodebuddy = runtime === \'codebuddy\';` alongside other runtime flags', '在 `install()` 函数（第 2394 行）中，与其他运行时标志一起添加 `const isCodebuddy = runtime === \'codebuddy\';`')
  .replace('**Commands installation** (line 2436-2504): CodeBuddy follows the Claude/Gemini `else` branch at line 2491. Since `isCodebuddy` is not any of the spe
